name: Caesar
description: Шифр Цезаря
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # No external dependencies required for this project.

dev_dependencies:
  test: ^1.21.0 # For unit testing